/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.admin;

import datos.ConectorBD;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import modulos.Peliculas;
import modulos.TablaGestionPeliculasModel;
import modulos.Usuarios;

/**
 *
 * @author ff_ma
 */
public class GestionarPeliculas extends javax.swing.JFrame {

    private Usuarios usuarios;
    private ConectorBD conectBD;
    private Peliculas peli;
    private TablaGestionPeliculasModel tablaModel;

    private JFileChooser elegirRuta;
    private int seleccion = 0;
    private File foto = null;

    /**
     * Creates new form BienvenidaUser
     */
    public GestionarPeliculas(Usuarios usuarios) {
        initComponents();
        this.usuarios = usuarios;
        conectBD = new ConectorBD();
        peli = new Peliculas();

        //creamos la tabla con DefaultTableModel
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jButtonFoto = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelDirector = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jLabelAnio = new javax.swing.JLabel();
        jTextFieldAnio = new javax.swing.JTextField();
        jLabelSinopsis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSinopsis = new javax.swing.JTextArea();
        jLabelGeneros = new javax.swing.JLabel();
        jLabelRangoEdad = new javax.swing.JLabel();
        jComboBoxRangoEdad = new javax.swing.JComboBox<>();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonAniadir = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelTituloPantalla = new javax.swing.JLabel();
        jCheckBoxGeneroComedia = new javax.swing.JCheckBox();
        jCheckBoxGeneroDramatica = new javax.swing.JCheckBox();
        jCheckBoxGeneroAccion = new javax.swing.JCheckBox();
        jCheckBoxRomantica = new javax.swing.JCheckBox();
        jCheckBoxGeneroThriller = new javax.swing.JCheckBox();
        jCheckBoxGeneroFantastica = new javax.swing.JCheckBox();
        jCheckBoxGeneroHistorica = new javax.swing.JCheckBox();
        jCheckBoxGeneroBelica = new javax.swing.JCheckBox();
        jCheckBoxGeneroAnimada = new javax.swing.JCheckBox();
        jCheckBoxGeneroBiografica = new javax.swing.JCheckBox();
        jLabelFoto = new javax.swing.JLabel();
        jButtonExaminar = new javax.swing.JButton();
        jLabelFotoSeleccionada = new javax.swing.JLabel();
        jPanelInferior = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jTextFieldBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOpcion = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuGestionar = new javax.swing.JMenu();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemPelis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("Titulo:");

        jLabelDirector.setText("Director:");

        jLabelAnio.setText("Año:");

        jLabelSinopsis.setText("Sinopsis:");

        jTextAreaSinopsis.setColumns(20);
        jTextAreaSinopsis.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSinopsis);

        jLabelGeneros.setText("Generos:");

        jLabelRangoEdad.setText("Rango Edad:");

        jComboBoxRangoEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los públicos", "+7", "+12", "+16", "+18" }));

        jLabelPrecio.setText("Precio:");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonAniadir.setText("Añadir");
        jButtonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jLabelTituloPantalla.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTituloPantalla.setText("GESTIONAR PELICULAS");

        jCheckBoxGeneroComedia.setText("Comedia");

        jCheckBoxGeneroDramatica.setText("Dramática");

        jCheckBoxGeneroAccion.setText("Acción");

        jCheckBoxRomantica.setText("Romántica");

        jCheckBoxGeneroThriller.setText("Thriller");

        jCheckBoxGeneroFantastica.setText("Fantástica");

        jCheckBoxGeneroHistorica.setText("Histórica");

        jCheckBoxGeneroBelica.setText("Bélica");

        jCheckBoxGeneroAnimada.setText("Animada");

        jCheckBoxGeneroBiografica.setText("Biográfica");

        jLabelFoto.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabelFoto.setText("Caratula:");

        jButtonExaminar.setText("Examinar...");
        jButtonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTituloPantalla)
                .addGap(112, 112, 112))
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addComponent(jLabelFoto)
                        .addGap(81, 81, 81)
                        .addComponent(jButtonExaminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFotoSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelDirector)
                            .addComponent(jLabelAnio)
                            .addComponent(jLabelSinopsis)
                            .addComponent(jLabelGeneros)
                            .addComponent(jLabelRangoEdad)
                            .addComponent(jLabelPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTitulo)
                                    .addComponent(jTextFieldDirector)
                                    .addComponent(jComboBoxRangoEdad, 0, 283, Short.MAX_VALUE)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxGeneroComedia)
                                    .addComponent(jTextFieldAnio, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                                    .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxGeneroAccion)
                                        .addComponent(jCheckBoxGeneroThriller))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxGeneroDramatica)
                                                .addComponent(jCheckBoxRomantica))
                                            .addComponent(jCheckBoxGeneroFantastica))
                                        .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxGeneroBelica)
                                                .addComponent(jCheckBoxGeneroBiografica)))))
                                .addComponent(jCheckBoxGeneroHistorica)
                                .addComponent(jCheckBoxGeneroAnimada))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonAniadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPantalla)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTitulo)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDirector)
                            .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnio)
                            .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSinopsis)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelGeneros))
                            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxGeneroComedia)
                                    .addComponent(jCheckBoxGeneroDramatica))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxGeneroAccion)
                            .addComponent(jCheckBoxRomantica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxGeneroThriller)
                            .addComponent(jCheckBoxGeneroFantastica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxGeneroHistorica)
                            .addComponent(jCheckBoxGeneroBelica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxGeneroAnimada)
                            .addComponent(jCheckBoxGeneroBiografica))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRangoEdad)
                            .addComponent(jComboBoxRangoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExaminar)
                    .addComponent(jLabelFoto)
                    .addComponent(jLabelFotoSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonAniadir)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonLimpiar))
                .addGap(38, 38, 38))
        );

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titulo", "Director", "Año", "Generos", "Rango de edad", "Precio" }));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInferiorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addGap(17, 17, 17))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );

        jMenuOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/opciones.png"))); // NOI18N

        jMenuItemInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/inicio.png"))); // NOI18N
        jMenuItemInicio.setText("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenuOpcion.add(jMenuItemInicio);

        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/salida.png"))); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpcion.add(jMenuItemSalir);

        jMenuBar.add(jMenuOpcion);

        jMenuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/perfil.png"))); // NOI18N
        jMenuPerfil.setText("Pefil");
        jMenuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPerfilActionPerformed(evt);
            }
        });
        jMenuBar.add(jMenuPerfil);

        jMenuGestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/gestionar.png"))); // NOI18N
        jMenuGestionar.setText("Gestionar");

        jMenuItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/usuario.png"))); // NOI18N
        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuGestionar.add(jMenuItemUsuarios);

        jMenuItemPelis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/peliculas.png"))); // NOI18N
        jMenuItemPelis.setText("Peliculas");
        jMenuItemPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPelisActionPerformed(evt);
            }
        });
        jMenuGestionar.add(jMenuItemPelis);

        jMenuBar.add(jMenuGestionar);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirActionPerformed
        aniadir();
    }//GEN-LAST:event_jButtonAniadirActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPerfilActionPerformed
        dispose();

        PerfilAdmin p = new PerfilAdmin(usuarios);
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuPerfilActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        dispose();

        GestionarUsuarios gu = new GestionarUsuarios(usuarios);
        gu.setLocationRelativeTo(null);
        gu.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPelisActionPerformed
        dispose();

        GestionarPeliculas pe = new GestionarPeliculas(usuarios);
        pe.setLocationRelativeTo(null);
        pe.setVisible(true);
    }//GEN-LAST:event_jMenuItemPelisActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        dispose();

        BienvenidoAdmin ba = new BienvenidoAdmin(usuarios);
        ba.setLocationRelativeTo(null);
        ba.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jButtonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExaminarActionPerformed
        examinarFoto();
    }//GEN-LAST:event_jButtonExaminarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarPelis();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int fila = jTable.getSelectedRow();
        if (fila != -1) {
            rellenarFormulario(fila);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void rellenarFormulario(int fila) {
        peli = new Peliculas();
        peli.setId_peli(Integer.parseInt(jTable.getValueAt(fila, 0).toString()));
        peli.setCaratula(jTable.getValueAt(fila, 1).toString());
        jButtonFoto.setIcon(new ImageIcon(new ImageIcon(System.getProperty("user.dir") + peli.getCaratula()).getImage().getScaledInstance(jButtonFoto.getWidth(), jButtonFoto.getHeight(), Image.SCALE_SMOOTH)));
        jTextFieldTitulo.setText(jTable.getValueAt(fila, 2).toString());
        jTextFieldDirector.setText(jTable.getValueAt(fila, 3).toString());
        jTextFieldAnio.setText(jTable.getValueAt(fila, 4).toString());
        jTextAreaSinopsis.setText(jTable.getValueAt(fila, 5).toString());
        rellenarCheckBoxGenero(jTable.getValueAt(fila, 6).toString());
        rellenarComboBoxRangoEdad(jTable.getValueAt(fila, 7).toString());
        jTextFieldPrecio.setText(jTable.getValueAt(fila, 8).toString());
    }

    private void examinarFoto() {
        //Seleccionamos la foto
        elegirRuta = new JFileChooser();
        elegirRuta.setDialogTitle("Selecciona la foto de perfil");
        elegirRuta.setFileFilter(new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif"));
        elegirRuta.setCurrentDirectory(new File(System.getProperty("user.dir") + "/Pictures"));
        seleccion = elegirRuta.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            foto = elegirRuta.getSelectedFile();
            if (foto != null) {
                ImageIcon icono = new ImageIcon(foto.getAbsolutePath());
                jLabelFotoSeleccionada.setText(foto.getName());
                jButtonFoto.setIcon(new ImageIcon(icono.getImage().getScaledInstance(jButtonFoto.getWidth(), jButtonFoto.getHeight(), Image.SCALE_SMOOTH)));
            }
        }
    }

    private String comprobarCheckBoxGenero() {
        String generos = null;
        if (jCheckBoxGeneroAccion.isSelected()) {
            if (generos != null) {
                generos += ", Acción";
            } else {
                generos += "Acción";
            }
        }
        if (jCheckBoxGeneroAnimada.isSelected()) {
            if (generos != null) {
                generos += ", Animada";
            } else {
                generos += "Animada";
            }
        }
        if (jCheckBoxGeneroBelica.isSelected()) {
            if (generos != null) {
                generos += ", Bélica";
            } else {
                generos += "Bélica";
            }
        }
        if (jCheckBoxGeneroBiografica.isSelected()) {
            if (generos != null) {
                generos += ", Biográfica";
            } else {
                generos += "Biográfica";
            }
        }
        if (jCheckBoxGeneroComedia.isSelected()) {
            if (generos != null) {
                generos += ", Comedia";
            } else {
                generos += "Comedia";
            }
        }
        if (jCheckBoxGeneroDramatica.isSelected()) {
            if (generos != null) {
                generos += ", Dramática";
            } else {
                generos += "Dramática";
            }
        }
        if (jCheckBoxRomantica.isSelected()) {
            if (generos != null) {
                generos += ", Romántica";
            } else {
                generos += "Romántica";
            }
        }
        if (jCheckBoxGeneroFantastica.isSelected()) {
            if (generos != null) {
                generos += ", Fantástica";
            } else {
                generos += "Fantástica";
            }
        }
        if (jCheckBoxGeneroHistorica.isSelected()) {
            if (generos != null) {
                generos += ", Histórica";
            } else {
                generos += "Histórica";
            }
        }
        if (jCheckBoxGeneroThriller.isSelected()) {
            if (generos != null) {
                generos += ", Thriller";
            } else {
                generos += "Thriller";
            }
        }
        if (!jCheckBoxGeneroThriller.isSelected() && !jCheckBoxGeneroHistorica.isSelected() && !jCheckBoxGeneroFantastica.isSelected() && !jCheckBoxRomantica.isSelected() && !jCheckBoxGeneroDramatica.isSelected() && !jCheckBoxGeneroComedia.isSelected() && !jCheckBoxGeneroBiografica.isSelected() && !jCheckBoxGeneroBelica.isSelected() && !jCheckBoxGeneroAnimada.isSelected() && !jCheckBoxGeneroAccion.isSelected()) {
            generos = null;
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar al menos un genero", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        return generos;
    }

    private void deseleccionarCheckBoxGenero() {
        if (jCheckBoxGeneroAccion.isSelected()) {
            jCheckBoxGeneroAccion.setSelected(false);
        }
        if (jCheckBoxGeneroAnimada.isSelected()) {
            jCheckBoxGeneroAnimada.setSelected(false);
        }
        if (jCheckBoxGeneroBelica.isSelected()) {
            jCheckBoxGeneroBelica.setSelected(false);
        }
        if (jCheckBoxGeneroBiografica.isSelected()) {
            jCheckBoxGeneroBiografica.setSelected(false);
        }
        if (jCheckBoxGeneroComedia.isSelected()) {
            jCheckBoxGeneroComedia.setSelected(false);
        }
        if (jCheckBoxGeneroDramatica.isSelected()) {
            jCheckBoxGeneroDramatica.setSelected(false);
        }
        if (jCheckBoxRomantica.isSelected()) {
            jCheckBoxRomantica.setSelected(false);
        }
        if (jCheckBoxGeneroFantastica.isSelected()) {
            jCheckBoxGeneroFantastica.setSelected(false);
        }
        if (jCheckBoxGeneroHistorica.isSelected()) {
            jCheckBoxGeneroHistorica.setSelected(false);
        }
        if (jCheckBoxGeneroThriller.isSelected()) {
            jCheckBoxGeneroThriller.setSelected(false);
        }
    }

    private void cargarTabla() {
        declararModelo();

        //añadimos el contenido
        conectBD.openBD();
        this.tablaModel.setFila(conectBD.selectPelis());
        conectBD.closeBD();
    }

    private void declararModelo() {
        //instanciamos el modelo de tabla creado
        this.tablaModel = new TablaGestionPeliculasModel();
        //permitimos la seleccion de la fila de la tabla
        jTable.setRowSelectionAllowed(true);
        //añadimos una interfaz que nos 
        //perimte elegir el modo de selecion de la tabla
        //hemos elegido el que nos permite 
        //"seleccionar un índice de lista a la vez"
        jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //añadimos el modelo a la tabla
        this.jTable.setModel(tablaModel);
    }

    private void limpiar() {
        peli = null;
        jTextAreaSinopsis.setText("");
        jTextFieldAnio.setText("");
        jTextFieldDirector.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldTitulo.setText("");
        jComboBoxRangoEdad.setSelectedIndex(0);
        deseleccionarCheckBoxGenero();
        foto = null;
        jLabelFotoSeleccionada.setText("");
        jButtonFoto.setIcon(new ImageIcon(new ImageIcon(System.getProperty("user.dir") + "/img/imgPelis/defaultPeli.jpeg").getImage().getScaledInstance(jButtonFoto.getWidth(), jButtonFoto.getHeight(), Image.SCALE_SMOOTH)));
    }

    private void aniadir() {
        peli = null;
        peli = new Peliculas();

        //Se comprueba que ha añadido todo
        if (!jTextFieldTitulo.getText().equals("") && !jTextFieldAnio.getText().equals("") && !jTextFieldDirector.getText().equals("") && comprobarCheckBoxGenero() != null && foto != null) {

            peli.setTitulo(jTextFieldTitulo.getText().replace(":", ""));
            peli.setDirector(jTextFieldDirector.getText());
            peli.setAnio(Integer.parseInt(jTextFieldAnio.getText()));
            peli.setCaratula(peli.ponerFoto(foto, peli.getTitulo()));
            peli.setGeneros(comprobarCheckBoxGenero());
            peli.setSinopsis(jTextAreaSinopsis.getText().replace("'", "\""));
            peli.setRango_edad((String) jComboBoxRangoEdad.getSelectedItem());
            peli.setPrecio(Double.parseDouble(jTextFieldPrecio.getText()));

            conectBD.openBD();
            conectBD.insertPelis(peli);
            conectBD.closeBD();

            JOptionPane.showMessageDialog(null, "Foto modificada con exito", "Exito al modificar perfil", JOptionPane.INFORMATION_MESSAGE);
            limpiar();

            //actualizamos los campos de la tabla
            cargarTabla();
        }
    }

    private void eliminar() {
        System.out.println(peli.getId_peli());
        conectBD.openBD();
        conectBD.deletePelis(peli.getId_peli());
        conectBD.closeBD();

        //actualizamos los campos de la tabla
        cargarTabla();

        limpiar();
    }

    private void modificar() {
        System.out.println(peli.getId_peli() + ", " + peli.getCaratula());

//        if (!jTextFieldTitulo.getText().equals("") || !jTextFieldAnio.getText().equals("") || !jTextFieldDirector.getText().equals("") || comprobarCheckBoxGenero() != null || foto != null ) {
        peli.setTitulo(jTextFieldTitulo.getText());
        peli.setDirector(jTextFieldDirector.getText());
        peli.setAnio(Integer.parseInt(jTextFieldAnio.getText()));
        peli.setGeneros(comprobarCheckBoxGenero());
        peli.setSinopsis(jTextAreaSinopsis.getText());
        peli.setRango_edad((String) jComboBoxRangoEdad.getSelectedItem());
        peli.setPrecio(Double.parseDouble(jTextFieldPrecio.getText()));

        if (foto != null) {
            peli.setCaratula(peli.ponerFoto(foto, peli.getId_peli() + ""));
            conectBD.openBD();
            conectBD.updateCARATULA(peli);
            conectBD.closeBD();
        }
        conectBD.openBD();
        conectBD.updatePelis(peli);
        conectBD.closeBD();

        JOptionPane.showMessageDialog(null, "Foto modificada con exito", "Exito al modificar perfil", JOptionPane.INFORMATION_MESSAGE);

        //actualizamos los campos de la tabla
        cargarTabla();

        limpiar();
//        }
    }

    private void buscarPelis() {
        switch ((String) jComboBoxBuscar.getSelectedItem()) {
            case "Titulo":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarTitulo(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Generos":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarGenero(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Rango de edad":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarRangoEdad(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Precio":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarPrecio(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Director":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarDirector(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Año":
                if (jTextFieldBuscar.getText() != null) {
                    declararModelo();
                    conectBD.openBD();
                    //añadimos los campos de la tabla
                    this.tablaModel.setFila(conectBD.buscarAnio(jTextFieldBuscar.getText()));
                    conectBD.closeBD();
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce lo que quieres buscar", "Error buscar", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }

    private void rellenarCheckBoxGenero(String generos) {
        String[] parts = generos.split(",");
        for (String part : parts) {
            if ("Acción".equals(part)) {
                jCheckBoxGeneroAccion.setSelected(true);
            }
            if ("Animada".equals(part)) {
                jCheckBoxGeneroAnimada.setSelected(true);
            }
            if ("Bélica".equals(part)) {
                jCheckBoxGeneroBelica.setSelected(true);
            }
            if ("Biográfica".equals(part)) {
                jCheckBoxGeneroBiografica.setSelected(true);
            }
            if ("Comedia".equals(part)) {
                jCheckBoxGeneroComedia.setSelected(true);
            }
            if ("Dramática".equals(part)) {
                jCheckBoxGeneroDramatica.setSelected(true);
            }
            if ("Romántica".equals(part)) {
                jCheckBoxRomantica.setSelected(true);
            }
            if ("Fantástica".equals(part)) {
                jCheckBoxGeneroFantastica.setSelected(true);
            }
            if ("Histórica".equals(part)) {
                jCheckBoxGeneroHistorica.setSelected(true);
            }
            if ("Thriller".equals(part)) {
                jCheckBoxGeneroThriller.setSelected(true);
            }
        }
    }

    private void rellenarComboBoxRangoEdad(String RangoEdad) {
        switch (RangoEdad) {
            case "Todos los públicos":
                jComboBoxRangoEdad.setSelectedIndex(0);
                break;
            case "+7":
                jComboBoxRangoEdad.setSelectedIndex(1);
                break;
            case "+12":
                jComboBoxRangoEdad.setSelectedIndex(2);
                break;
            case "+16":
                jComboBoxRangoEdad.setSelectedIndex(3);
                break;
            case "+18":
                jComboBoxRangoEdad.setSelectedIndex(4);
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonExaminar;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JCheckBox jCheckBoxGeneroAccion;
    private javax.swing.JCheckBox jCheckBoxGeneroAnimada;
    private javax.swing.JCheckBox jCheckBoxGeneroBelica;
    private javax.swing.JCheckBox jCheckBoxGeneroBiografica;
    private javax.swing.JCheckBox jCheckBoxGeneroComedia;
    private javax.swing.JCheckBox jCheckBoxGeneroDramatica;
    private javax.swing.JCheckBox jCheckBoxGeneroFantastica;
    private javax.swing.JCheckBox jCheckBoxGeneroHistorica;
    private javax.swing.JCheckBox jCheckBoxGeneroThriller;
    private javax.swing.JCheckBox jCheckBoxRomantica;
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JComboBox<String> jComboBoxRangoEdad;
    private javax.swing.JLabel jLabelAnio;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFotoSeleccionada;
    private javax.swing.JLabel jLabelGeneros;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelRangoEdad;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloPantalla;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuGestionar;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemPelis;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOpcion;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextAreaSinopsis;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
