/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import datos.ConectorBD;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modulos.Usuarios;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author ff_ma
 */
public class JDialogRegistrarse extends javax.swing.JDialog {

    private File foto;

    /**
     * Creates new form JDialogRegistrarse
     */
    public JDialogRegistrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jPasswordFieldPwd = new javax.swing.JPasswordField();
        jButtonFotoExaminar = new javax.swing.JButton();
        jButtonRegistrarse = new javax.swing.JButton();
        jButtonFotoUsuario = new javax.swing.JButton();
        jLabelFotoSeleccionada = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 380));

        jPanel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 800));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitulo.setText("¿Quieres registrarte?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 32, 13, 0);
        jPanel1.add(jLabelTitulo, gridBagConstraints);

        jLabelNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 13, 0, 13);
        jPanel1.add(jLabelNombre, gridBagConstraints);

        jLabelApellido.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 13, 0, 13);
        jPanel1.add(jLabelApellido, gridBagConstraints);

        jLabelCorreo.setText("Correo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 13, 0, 13);
        jPanel1.add(jLabelCorreo, gridBagConstraints);

        jLabelContrasenia.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 13, 0, 13);
        jPanel1.add(jLabelContrasenia, gridBagConstraints);

        jLabelFoto.setText("Foto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 13, 0, 13);
        jPanel1.add(jLabelFoto, gridBagConstraints);

        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jTextFieldNombre, gridBagConstraints);

        jTextFieldApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidosFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jTextFieldApellidos, gridBagConstraints);

        jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jTextFieldCorreo, gridBagConstraints);

        jPasswordFieldPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPwdFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jPasswordFieldPwd, gridBagConstraints);

        jButtonFotoExaminar.setText("Examinar..");
        jButtonFotoExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoExaminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jButtonFotoExaminar, gridBagConstraints);

        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jButtonRegistrarse, gridBagConstraints);

        jButtonFotoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgIconos/user.jpeg"))); // NOI18N
        jButtonFotoUsuario.setMaximumSize(new java.awt.Dimension(150, 250));
        jButtonFotoUsuario.setMinimumSize(new java.awt.Dimension(100, 150));
        jButtonFotoUsuario.setPreferredSize(new java.awt.Dimension(150, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 31;
        jPanel1.add(jButtonFotoUsuario, gridBagConstraints);

        jLabelFotoSeleccionada.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        jLabelFotoSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFotoSeleccionada.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jLabelFotoSeleccionada, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFotoExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoExaminarActionPerformed
        examinarFoto();
    }//GEN-LAST:event_jButtonFotoExaminarActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        if (jTextFieldNombre.getText().length() != 0 && jTextFieldApellidos.getText().length() != 0 && jTextFieldCorreo.getText().length() != 0 && jPasswordFieldPwd.getText().length() != 0) {
            if (jTextFieldCorreo.getText().contains("@") && jTextFieldCorreo.getText().contains(".")) {
                registarse();
            } else {
                JOptionPane.showMessageDialog(null, "Error en el campo correo, hay que introducir un correo", "Error al introducir el correo", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error algún campo está vacío", "Error de campo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jTextFieldApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidosFocusLost
        if (jTextFieldApellidos.getText().length() == 0) {
            jTextFieldApellidos.setBackground(Color.red);
            jTextFieldApellidos.setForeground(Color.white);
        } else {
            jTextFieldApellidos.setForeground(Color.black);
            jTextFieldApellidos.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldApellidosFocusLost

    private void jTextFieldCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoFocusLost
        //comprobamos que no este vacio y sea un correo
        if (jTextFieldCorreo.getText().length() == 0 && !jTextFieldCorreo.getText().contains("@") && !jTextFieldCorreo.getText().contains(".")) {
            jTextFieldCorreo.setBackground(Color.red);
            jTextFieldCorreo.setForeground(Color.white);
        } else {
            jTextFieldCorreo.setForeground(Color.black);
            jTextFieldCorreo.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldCorreoFocusLost

    private void jPasswordFieldPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPwdFocusLost
        if (jPasswordFieldPwd.getText().length() == 0) {
            jPasswordFieldPwd.setBackground(Color.red);
            jPasswordFieldPwd.setForeground(Color.white);
        } else {
            jPasswordFieldPwd.setForeground(Color.black);
            jPasswordFieldPwd.setBackground(Color.white);
        }
    }//GEN-LAST:event_jPasswordFieldPwdFocusLost

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().length() == 0) {
            jTextFieldNombre.setBackground(Color.red);
            jTextFieldNombre.setForeground(Color.white);
        } else {
            jTextFieldNombre.setForeground(Color.black);
            jTextFieldNombre.setBackground(Color.white);
        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void registarse() {
        //declaramos variables que vamos a necesitar
        ConectorBD conectBD = new ConectorBD();
        Usuarios u = new Usuarios();

        //recogemos la informacion introducida
        u.setNombre(jTextFieldNombre.getText());
        u.setApellido(jTextFieldApellidos.getText());
        u.setCorreo(jTextFieldCorreo.getText());
        //contraseña codificada
        u.setPwd(DigestUtils.md5Hex(jPasswordFieldPwd.getText()));
        u.setIdRol(0); //sin rol
        u.setActivo(0); //sin activar

        //ponemos la foto e insertamos el usuario
        if (foto != null) {
            u.setFoto(u.ponerFoto(foto, u.getId_usuario() + ""));

            conectBD.openBD();
            conectBD.insertUsuarios(u);
            conectBD.closeBD();
        } else {
            foto = new File(System.getProperty("user.dir") + "/img/imgIconos/user.jpeg");
            u.setFoto(u.ponerFoto(foto, u.getCorreo()));

            conectBD.openBD();
            conectBD.insertUsuarios(u);
            conectBD.closeBD();
        }

        dispose();
    }

    private void examinarFoto() {
        //Seleccionamos la foto
        JFileChooser elegirRuta = new JFileChooser();
        elegirRuta.setDialogTitle("Selecciona la foto de perfil");
        elegirRuta.setFileFilter(new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif"));
        elegirRuta.setCurrentDirectory(new File(System.getProperty("user.dir") + "/Pictures"));
        if (elegirRuta.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            foto = elegirRuta.getSelectedFile();
            if (foto != null) {
                ImageIcon icono = new ImageIcon(foto.getAbsolutePath());
                jLabelFotoSeleccionada.setText(foto.getName());
                jButtonFotoUsuario.setIcon(new ImageIcon(icono.getImage().getScaledInstance(jButtonFotoUsuario.getWidth(), jButtonFotoUsuario.getHeight(), Image.SCALE_SMOOTH)));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFotoExaminar;
    private javax.swing.JButton jButtonFotoUsuario;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFotoSeleccionada;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPwd;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
